// Meridian AI — shared decision item schema.
//
// Every module adapter should output DecisionItem[] regardless of vertical.
// PlatformShell renders this shape directly.
//
// Field names currently match the legacy MODULES mock data (arv/mao/ask) so
// the detail-panel rendering does not need to change. A future migration may
// rename these to primary/secondary/tertiary; the per-module label remapping
// in PlatformShell already handles the semantic difference per vertical.

export type DecisionLabelType = "green" | "amber" | "red";

// ── Source-aware valuation output ──────────────────────────────────────
// Every actionable item carries one of these. The engine NEVER claims live
// market certainty unless the underlying data genuinely supports it; instead
// it reports what it used, when, how confident it is, and how that confidence
// has been propagated into the execution ladder.
export type SourceQuality = "HIGH" | "MEDIUM" | "LOW";

export type Valuation = {
  valuationTimestamp: string;        // ISO — when this valuation was computed
  sourceRecencyHours: number | null; // age of the underlying source data
  sourceQuality: SourceQuality;
  confidenceScore: number;           // 0-100
  confidenceLabel: string;           // human verdict ("high-confidence valuation", etc.)
  compCount: number;                 // # comps backing the estimate
  valuationMethod: string;           // honest description of how value was derived
  estimatedFairValue: number;        // confidence-adjusted fair value (the working anchor)
  valuationLow: number;              // dispersion floor — wider when confidence is lower
  valuationHigh: number;             // dispersion ceiling
  rationale: string;                 // one-line plain-English explanation
  // Vertical-specific (optional) ──
  estimatedMarketValue?: number;     // watches: condition-adjusted spot value
  conditionBand?: string;            // watches: "full set / unpolished / serviced", etc.
  estimatedAsIsValue?: number;       // real estate: pre-rehab value
  estimatedARV?: number;             // real estate: stabilized after-repair value
  // ── Fragility (operator-grade weakness audit) ──
  // Independent of confidence: confidence asks "how sure are we in fair value?",
  // fragility asks "how many critical assumptions are doing all the work?".
  // High fragility = even if we're right, we're right by accident.
  fragilityScore?: number;           // 0-100, higher = more fragile
  fragilityFlags?: string[];         // human-readable dominant-assumption notes
};

export type DecisionItem = {
  id: number | string;
  title: string;
  sub: string;
  score: number;
  label: string;
  labelType: DecisionLabelType;
  tag?: string;
  arv?: string;        // primary metric (ARV / Price / ARR)
  mao?: string;        // secondary metric (MAO / Rel.Str. / Expansion)
  ask?: string;        // tertiary metric (Asking / Price / Status)
  risk?: string;
  nextAction?: string;
  riskFactors?: string[];
  thesis?: string;            // one-line "why this matters" explanation
  platformMetrics?: string;   // engine-computed metrics summary (mono, multi-line OK)
  maxBuyPrice?: number;       // negotiation ceiling: highest price to hit target net margin
  riskAdjustedReturn?: number;// annualized return %, hold-time-aware (netMargin × 365 / holdDays)
  buyPriceUsd?: number;       // raw acquisition cost (numeric, for capital allocation engines)
  expectedNetDollar?: number; // expected net hold-period dollar profit (after friction)
  trustScore?: number;        // 0-100 from the trust/scam-filter engine
  trustTier?: string;         // "TRUSTED" | "CAUTION" | "SOFT_REJECT" | "REJECTED"
  trustNote?: string;         // human-readable trust verdict line
  trustReasons?: string[];    // discrete list of issues found (drives the bulleted breakdown)
  valuation?: Valuation;      // source-aware, confidence-adjusted fair value
  // ── Unified acquisition plan (only for actionable items) ──
  // Replaces the prior split between execution and negotiation. One coherent
  // operator playbook covering price ladder, negotiation posture, hold/exit,
  // and operator priority. Generated by lib/scoring/acquisition.ts.
  acquisitionPlan?: {
    openingOffer: number;
    targetBuy: number;
    hardCeiling: number;           // SACRED — never above
    walkAwayTrigger: string;
    negotiationStyle: string;      // Aggressive | Confident | Balanced | Patient | Walk-ready
    negotiationReasoning: string;
    likelyObjections: string[];
    counterStrategy: string;
    followUpWindowHours: number;
    estimatedHoldDays: number;
    exitPlatform: string;
    exitReasoning: string;
    urgency: string;               // act-now | this-week | this-month | passive
    capitalPriority: string;       // anchor | core | satellite | skip
    // ── Adaptive negotiation behavior ──
    primaryLeverage: string;
    leverageStrength: number;      // 1-10
    fallbackLeverage: string;
    negotiationPhase: string;      // entry | counter | walk
    capitalContext: string;        // anchor | optional | last-slot
    // ── Unified decision (executive summary — single deterministic output) ──
    decision: {
      decision: string;            // STRONG BUY | BUY | MONITOR | PASS | AVOID
      conviction: number;          // 0-10
      // Compressed single-action verdict — the engine's dominant play.
      // EXECUTE_NOW | EXECUTE_CONTROLLED | PROBE | WAIT | WALK
      dominantAction: string;
      execution: {
        timing: string;            // IMMEDIATE | THIS_WEEK | WAIT
        maxBuyPrice: number;       // hard ceiling — sacred
        walkAwayPrice: number;     // 2% above ceiling
      };
      negotiation: {
        anchorPrice: number;       // opening counter
        strategy: string;          // AGGRESSIVE | CONTROLLED | PASSIVE | WALK
        reasoning: string;         // compressed: "ACTION — qualifier"
        // Relationship-coherent posture for this action — single label,
        // same voice across every operator-facing surface.
        posture: string;
      };
    };
  };
  // ── Persisted negotiation memory (per item) ──
  negotiationState?: {
    currentPhase?: string;
    lastActionTaken?: string;
    sellerResponse: string;        // none | rejected | countered | accepted | stalled
    timeSinceLastActionHours: number;
    sellerCounterPrice?: number;
    lastOfferSent?: number;
    lastUpdated?: string;          // ISO timestamp
  };
};
